project:
  type: website
  output-dir: docs

website:
  title: "Helen Schmidt"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: portfolio.qmd
        text: Portfolio
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    

editor: source

