project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - '!portafolio.qmd'
    - publications.qmd
    - resources.qmd
  
website:
  title: "Felix Ipanaque"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      #- href: portafolio.qmd
      #  text: portafolio
      - href: publications.qmd
        text: Events & Talks 
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: spacelab
      dark: solar
    css: styles.css
    toc: true
    

editor: source

