---
title: "About Me"
format: 
  html:
    page-layout: full
---

I earned my bachelor in Industrial & Systems engineer at [Universidad de Piura](https://www.udep.edu.pe/) in Peru, I hold a MBA from [Universidad Los Andes](https://uniandes.edu.co/en) in Colombia. I am a Neuroscience PhD candidate at the [Univeristy of Tsukuba](https://www.tsukuba.ac.jp/en/) in Japan. Previously, [tech entrepreneur](https://www.youtube.com/watch?v=M_PyRRqietw). I am currently living in Tsukuba, Japan's renowned science city, where I am actively developing my next business idea. 

I am working on a project aimed at advancing the collection of emotional brain wave data during sleep, with the goal of improving our understanding of how emotions influence behavior. This work could lead to the development of brain-computer interfaces that enhance our ability to diagnose and treat brain disorders, such as depression and anxiety. This would be possible by enabling more precise monitoring and intervention based on emotional brain activity.

Previously, I founded PickApp [(now Scharff Express)](https://www.holascharff.com/en/solutions/people-and-entrepreneurs/){target="_blank"}, which later became a leading provider of software solutions for the transportation industry. [PickApp was acquired by Scharff Inc.](https://www.facebook.com/felixipanaquear/photos/a.314611525680937/335734870235269/){target="_blank"} (FedEx Representative - Peru) in December 2017, hitting a milestone within the startup ecosystem in Peru. You can see the news [here.](https://gestion.pe/blog/innovar-o-ser-cambiado/2018/07/laboratorios-de-innovacion-logistica.html?ref=gesr&fbclid=IwAR3XA5DaiIfIoldObCHaV9RyBNn3afAwRiTDeYBsFWQEOUXv8eAQki7hXZ4#utm_source=facebook&amp;utm_medium=organic&amp;utm_campaign=innovacion-%20scharfflab){target="_blank"}.This project was part of the 2nd generation of [StartUp Peru](https://startup.proinnovate.gob.pe/) and [Ynnovadores](https://losynnovadores.com/).

Throughout my career, I have developed deep understanding of the entire value chain from concept to launch, business development, strategic innovation and key partnerships.

I have managed and executed over 100 improvement projects across Mexico, Colombia, Peru, and Spain, many of which continue to deliver value today. I am passionate about helping businesses and entrepreneurs develop and implement digital strategies, leveraging design thinking and lean startup methodologies.