---
title: "Publications and Selected Presentations"
output:
  html_document: 
    includes:
      after_body: footer.html
    theme: cosmo
---

<br>

## Manuscripts in Preparation / Under Review
<font size="2">
+ *denotes equal contribution* | # *denotes trainee*
</font>

<font size="3.5">
**Schmidt, H.^+^**, Tran, S.^+#^, Medaglia, J., Ulichney, V., & Helion, C. (2022). [Conversational linguistic features predict social network learning.](https://psyarxiv.com/fn4my/){target="_blank" style="color:Tomato"} *Under Review*. &nbsp; <a href="https://osf.io/8wqhb/" target="_blank" class="fas fa-code" style="color:Tomato"></a> &nbsp; <a href="https://github.com/hschmidt12/NLP-Social-Network-Learning" target="_blank" class="fab fa-github" style="color:Tomato"></a> 

Mitchell, W.J., Stasiak, J., Martinez, S.A., Cliver, K., Gregory, D.F., Reisman, S., **Schmidt, H.**, Murty, V.P., & Helion, C. (2022). [Emotion regulation strategy usage in a quasi-naturalistic context.](https://psyarxiv.com/23wtz/){target="_blank" style="color:Tomato"} *Under Review*. &nbsp; <a href="https://osf.io/j5sku/?view_only=" target="_blank" class="fas fa-code" style="color:Tomato"></a>

**Schmidt, H.^+^**, Cooper, R.A.^+^, & Ritchey, M. (2021). Temporal dynamics supporting the multidimensional qualities of episodic memory. *In Preparation*.


</font>
<br>

## Selected Poster Presentations 
<font size="3.5">

Click [here](selected-posters.html){target="_blank" style="color:Tomato"} to see a selection of my poster presentations. All presentations are listed on my [CV](files/SchmidtCV-Website.pdf){target="_blank" style="color:Tomato"}.

</font>
