---
title: "Creating Websites with R Markdown"
output:
  html_document:
    includes:
      after_body: "footer.html"
---

<br>
<font size="3.5">
Page adapted from information and advice in [Emily Zabor's website tutorial](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#Types_of_websites){target="_blank" style="color:Tomato"}. Please note that this tutorial only reflects my own experience building a website using GitHub pages and R Markdown. It is by no means the only way to set up a website nor is it the only way to build a website using these specific tools. 
<br>

## Set up GitHub
This tutorial focuses on hosting websites through GitHub pages. If you don't have a GitHub account, you can set one up [here](https://github.com/join){target="_blank" style="color:Tomato"}. If you already have a GitHub account, log in and navigate to your profile. Now select "Repositories" and click the green "New" button to set up a new repository.

Importantly, this repository must be named using the following format: *github-username*.github.io (where *github-username* is your own username). The name must exactly match this format in order for GitHub to recognize it as a GitHub pages repository. 

You should also select "Add a README file" when initializing this repository. You can choose whether the repository is public or private. Once you're done, select "Create repository."
<br>

### Set up repository locally
Next, you should clone this repository locally. I've found that the easiest way to do this is via the terminal. 

1. Navigate to the local folder you want to host this repository in using the terminal. 
2. On GitHub, copy the path to this repository by selecting the green "Code" button and copying the HTTPS path. 
3. Back in the terminal window, type **git clone** and paste the repository path. Press enter. You should now see a subfolder that matches the respository name locally!
<br>

## Create an R project
Now you're ready to begin building your website in R! I highly recommend working in RStudio. Create a new project by selecting File > New Project and save this project in your newly created git folder. See Emily Zabor's [tutorial](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#Why_do_I_need_an_R_Project){target="_blank" style="color:Tomato"} for more information about why an R Project is useful. 
<br>

## Create initial content pages
There are two key ingredients to an R Markdown website that you will need to create first. The first is a _site.yml file, which controls the layout and theme of your website. The second is a index.Rmd file, which is your home page. You should not change the names of these two files, but you will be able to customize the names of any additional pages you create. I will be creating a website to highlight my favorite coffee and cafes!
<br>

### _site.yml setup
There are a lot of ways to customize your website, but let's start with a simple layout that has a website title, a navigation bar with two pages, and a specified website theme. 

```{verbatim}
name: "Coffee Website"
navbar:
  title: "My Coffee Website"
  right:
    - text: "Home"
      href: index.html
    - text: "Cafes"
      href: cafes.html

output:
  html_document:
    theme: paper
```

You can see available themes by typing **rmarkdown:::themes()** into the RStudio console, or see the list below.
```{verbatim}
"default"  "bootstrap"  "cerulean"  "cosmo"  "darkly"  "flatly"  "journal"  "lumen"  "paper"  "readable"  "sandstone"  "simplex"  "spacelab"  "united"  "yeti" 
```
<br>

### index.Rmd setup
Now let's define the content on the homepage. To do this, I'm going to create a new R notebook by selecting File > New File > R Notebook. 
```{verbatim}
---
title: "My Coffee Website"
---

Welcome to my coffee website!
```

To make this into a page that a browser recognizes, I need to knit this markdown to an HTML file. Make sure you have the **knitr** package installed. If I select Knit > Knit to HTML, two things happen. One, a new file called index.html appears in my website directory. Two, that index.html opens in a new window. This and other HTML files are what will be displayed when your website is online.

You can create additional pages and add them to your navigation bar. Just make sure you also update your _site.yml file to display these additional pages.






